name: ClearIntentions
favicon: null
layout_spectrum: 0
typography_spectrum: 0.59608
title: Clear Intentions Hypnosis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020202'
    - '#ababc9'
    - '#856f39'
    - '#5b203a'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
